
site_name: AGS4
theme:
  name: mkdocs
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: brown
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: brown
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  extra:
    version:
      provider: mike
  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo
  markdown_extensions:
    - attr_list
  extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js